spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver #net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:mariadb://sleepycat1.cafe24.com/sleepycat1 #jdbc:log4jdbc:mariadb://sleepycat1.cafe24.com/sleepycat1 
    username: sleepycat1
    password: Goodguy1010!
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy  #org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:log4jdbc:mariadb://192.168.25.59:3306/sample 
#    username: root
#    password: qwer1234
    
    
dbconfig:
  db1MapperLocation: classpath*:mapper/maria/**/*.xml